version: '3.7'

volumes:
  # We'll define a volume that will store the data from the mongo databases:
  mongodb-data: {}
  redis-data: {}

services:
  frontend:
    environment:
      # more options in application.example.yml
      - UNICORN_WORKERS=3
      - MONGODB_URI=mongodb://mongo_server/cenit
      - REDIS_HOST=redis
    build: ./cenit_web
    image: cenit_web
    ports:
      - "80:8080"
    depends_on:
      - mongo_server
      - redis

  background:
    environment:
      - SKIP_DB_INITIALIZATION=false
      - SKIP_RABBIT_MQ=false
      - SCHEDULER_LOOKUP_INTERVAL=8
      - UNICORN_WORKERS=4
      - MAXIMUM_UNICORN_CONSUMERS=4
      - REDIS_HOST=redis
      - MONGODB_URI=mongodb://mongo_server/cenit
      - RABBITMQ_BIGWIG_TX_URL=amqp://cenit_rabbit:cenit_rabbit@rabbitmq/cenit_rabbit_vhost
    build: ./cenit
    image: cenit
    depends_on:
      - mongo_server
      - redis
      - rabbitmq

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_PASS=cenit_rabbit
      - RABBITMQ_DEFAULT_USER=cenit_rabbit
      - RABBITMQ_DEFAULT_VHOST=cenit_rabbit_vhost
    labels:
        NAME: "rabbitmq-server"

  mongo_server:
    image: mongo:3.6
    volumes:
      # We'll mount the 'mongodb-data' volume into the location mongodb stores it's data:
      - mongodb-data:/data/db

  redis:
    image: redis:5
    volumes:
      - redis-data:/data
    command: ["redis-server", "--appendonly", "yes"]
